version: "3.8"
services:
  server:
    build: .
    container_name: tra-server
    ports:
      - 4000:4000
    depends_on:
      - db
      - redis
      - mongo-db
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - .env:/app/.env
      - ./upload:/app/upload
    restart: unless-stopped
  db:
    image: postgres:14.10
    container_name: tra-db
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql
  mongo-db:
    image: mongo:latest
    container_name: tra-mongo
    restart: always
    ports:
      - '2701:2701'
    environment:
      MONGO_USER: mongo
      MONGO_PASSWORD: mongo
  redis:
    image: redis:5
    container_name: tra-redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=local:tra-redis:6379
    ports:
      - 8082:8081
    depends_on:
      - redis
volumes:
  postgresdata:
